name: ${name}
version: ${version}
main: ${groupId}.${artifactId}.${name}Plugin
description: ${description}
author: ${author}
permissions:
    announce.recieve:
        description: Allows you to recieve the broadcasts
        default: true